Repository exercism/wasm, pull requests merged in 2023-11, with the labels that each got.

#84 CI: pin GitHub Actions runners
  .github/workflows/test.yml
Labels: x:size/tiny

#86 CI: pin GitHub Actions workflows
  .github/workflows/test.yml
Labels: x:size/tiny

#87 chore: Update wasm-lib to 0.2.0 across exercises
  exercises/practice/acronym/acronym.spec.js
  exercises/practice/acronym/package.json
  exercises/practice/all-your-base/all-your-base.spec.js
  exercises/practice/all-your-base/package.json
  exercises/practice/armstrong-numbers/armstrong-numbers.spec.js
  exercises/practice/armstrong-numbers/package.json
  exercises/practice/bank-account/bank-account.spec.js
  exercises/practice/bank-account/package.json
  exercises/practice/binary-search/binary-search.spec.js
  exercises/practice/binary-search/package.json
  exercises/practice/circular-buffer/circular-buffer.spec.js
  exercises/practice/circular-buffer/package.json
  exercises/practice/collatz-conjecture/collatz-conjecture.spec.js
  exercises/practice/collatz-conjecture/package.json
  exercises/practice/darts/darts.spec.js
  exercises/practice/darts/package.json
  exercises/practice/difference-of-squares/difference-of-squares.spec.js
  exercises/practice/difference-of-squares/package.json
  exercises/practice/grains/grains.spec.js
  exercises/practice/grains/package.json
  exercises/practice/hamming/hamming.spec.js
  exercises/practice/hamming/package.json
  exercises/practice/hello-world/hello-world.spec.js
  exercises/practice/hello-world/package.json
  exercises/practice/leap/leap.spec.js
  exercises/practice/leap/package.json
  exercises/practice/nucleotide-count/nucleotide-count.spec.js
  exercises/practice/nucleotide-count/package.json
  exercises/practice/pangram/package.json
  exercises/practice/pangram/pangram.spec.js
  exercises/practice/pop-count/package.json
  exercises/practice/pop-count/pop-count.spec.js
  exercises/practice/raindrops/package.json
  exercises/practice/raindrops/raindrops.spec.js
  exercises/practice/resistor-color/package.json
  exercises/practice/resistor-color/resistor-color.spec.js
  exercises/practice/reverse-string/package.json
  exercises/practice/reverse-string/reverse-string.spec.js
  exercises/practice/rna-transcription/package.json
  exercises/practice/rna-transcription/rna-transcription.spec.js
  exercises/practice/rotational-cipher/package.json
  exercises/practice/rotational-cipher/rotational-cipher.spec.js
  exercises/practice/square-root/package.json
  exercises/practice/square-root/square-root.spec.js
  exercises/practice/triangle/package.json
  exercises/practice/triangle/triangle.spec.js
  exercises/practice/two-fer/package.json
  exercises/practice/two-fer/two-fer.spec.js
  package-lock.json
  package.json
Labels: x:size/tiny

#88 chore: Add package.json as invalidator file
  exercises/practice/acronym/.meta/config.json
  exercises/practice/all-your-base/.meta/config.json
  exercises/practice/armstrong-numbers/.meta/config.json
  exercises/practice/bank-account/.meta/config.json
  exercises/practice/binary-search/.meta/config.json
  exercises/practice/circular-buffer/.meta/config.json
  exercises/practice/collatz-conjecture/.meta/config.json
  exercises/practice/darts/.meta/config.json
  exercises/practice/difference-of-squares/.meta/config.json
  exercises/practice/grains/.meta/config.json
  exercises/practice/hamming/.meta/config.json
  exercises/practice/hello-world/.meta/config.json
  exercises/practice/leap/.meta/config.json
  exercises/practice/nucleotide-count/.meta/config.json
  exercises/practice/pangram/.meta/config.json
  exercises/practice/pop-count/.meta/config.json
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/resistor-color/.meta/config.json
  exercises/practice/reverse-string/.meta/config.json
  exercises/practice/rna-transcription/.meta/config.json
  exercises/practice/rotational-cipher/.meta/config.json
  exercises/practice/square-root/.meta/config.json
  exercises/practice/triangle/.meta/config.json
  exercises/practice/two-fer/.meta/config.json
Labels: x:size/tiny

#89 Update Dependencies to parity with JS track
  .github/workflows/test.yml
  exercises/practice/acronym/package.json
  exercises/practice/all-your-base/package.json
  exercises/practice/armstrong-numbers/package.json
  exercises/practice/bank-account/package.json
  exercises/practice/binary-search/package.json
  exercises/practice/circular-buffer/package.json
  exercises/practice/collatz-conjecture/package.json
  exercises/practice/darts/package.json
  exercises/practice/difference-of-squares/package.json
  exercises/practice/grains/package.json
  exercises/practice/hamming/package.json
  exercises/practice/hello-world/package.json
  exercises/practice/leap/package.json
  exercises/practice/nucleotide-count/package.json
  exercises/practice/pangram/package.json
  exercises/practice/pop-count/package.json
  exercises/practice/raindrops/package.json
  exercises/practice/resistor-color/package.json
  exercises/practice/reverse-string/package.json
  exercises/practice/rna-transcription/package.json
  exercises/practice/rotational-cipher/package.json
  exercises/practice/square-root/package.json
  exercises/practice/triangle/package.json
  exercises/practice/two-fer/package.json
  package-lock.json
  package.json
Labels: x:size/small

#90 Docs/wat function comments
  exercises/practice/acronym/acronym.wat
  exercises/practice/all-your-base/all-your-base.wat
  exercises/practice/armstrong-numbers/armstrong-numbers.wat
  exercises/practice/bank-account/bank-account.wat
  exercises/practice/binary-search/binary-search.wat
  exercises/practice/circular-buffer/circular-buffer.wat
  exercises/practice/collatz-conjecture/collatz-conjecture.wat
  exercises/practice/darts/darts.wat
  exercises/practice/difference-of-squares/difference-of-squares.wat
  exercises/practice/grains/grains.wat
  exercises/practice/hamming/hamming.wat
  exercises/practice/hello-world/hello-world.wat
  exercises/practice/leap/leap.wat
  exercises/practice/nucleotide-count/nucleotide-count.wat
  exercises/practice/pangram/pangram.wat
  exercises/practice/pop-count/pop-count.wat
  exercises/practice/raindrops/raindrops.wat
  exercises/practice/resistor-color/resistor-color.wat
  exercises/practice/reverse-string/reverse-string.wat
  exercises/practice/rna-transcription/rna-transcription.wat
  exercises/practice/rotational-cipher/rotational-cipher.wat
  exercises/practice/square-root/square-root.wat
  exercises/practice/triangle/triangle.wat
  exercises/practice/two-fer/two-fer.wat
  exercises/shared/.docs/help.md
Labels: x:size/medium

#93 Update grains.wat - typo in "total" description
  exercises/practice/grains/grains.wat
Labels: x:size/tiny
